---
title: "CS Core"
output: github_document
---

<!-- "'God blesses those who are poor and realize their need for him, for the Kingdom of Heaven is theirs...'" (Matthew 5:3 NLT) -->

1. Basic notions: sample spaces, events probability, conditional probability, Bayes' rule

#### Definitions

Sample space:

Event:

Simple event:

Sample points:

   a\. Translate a prose description of a probabilistic process into a formal setting of sample spaces, outcome
   probabilities, and events.

*Problem statement 1*:

Consider the experiment of rolling a pair of dice. Suppose that we are interested in the sum of the face values showing on
the dice.

a\. How many sample points are possible? (*Hint*: Use the counting rule for multiple-step experiments.)

<hr>
COUNTING RULE FOR MULTIPLE-STEP EXPERIMENTS (AKA THE PRODUCT RULE):

(n~1~)(n~2~)...(n~k~) where *k* is the number sequence of steps and n~k~ is the possible outcome
<hr>

*k* = 2, n~1~ = 6, n~2~ = 6, (6)(6) = 36.

b\. List the sample points.

*S* = {(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6)
       (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6)
       (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6)
       (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6)
       (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6)
       (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)}

c\. What is the probability of obtaining a value of 7?

*P*(7) = 6/36 = 1/6 = 0.167 = 16.7%

d\. What is the probability of obtaining a value of 9 or greater?

*P*(9 or greater) = 10/36 = 5/18 = 0.278 = 27.8%

e\. Because each roll has six possible even values (2, 4, 6, 8, 10, and 12) and only five possible odd values (3, 5, 7, 9,
and 11), the dice should show even values more often than odd values. Do you agree with this statement? Explain.

*P*(even) = 18/36 = 0.500 = 50%, *P*(odd) = 18/36 = 0.500 = 50%. The chances of rolling either even or odd are equal.

f\. What method did you use to assign the probabilities requested?

The classical method

   b. Calculate the probability of simple events.
   c. Determine whether two events are independent.
   d. Compute conditional probabilities, including through applying (and explaining) Bayes' Rule.

